In [1]:
import numpy as np

In [2]:
def ReLU(z):
    return np.maximum(0, z)

In [3]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [4]:
def compute_error(T, O):
    return 0.5 * (np.square(T-O))

In [5]:
def RelU_gradient(Z):
    return (Z>=0).astype(float)

**Forward pass**

In [6]:
A0 = np.array([[1],[2]]) # input layer
T = np.array([[1,0]]).T # the target

In [7]:
W1 = np.array([[0.1,0.2,0.3,0.4], [0.5,0.6,0.7,0.8]]).T # first hidden layer weights
B1 = np.zeros((4,1)) # first hidden layer bias
W2 = np.array([[0.1,0.2,0.3,0.4], [0.5,0.6,0.7,0.8]]) # output weights
B2 = 0 # output bias

In [10]:
Z1 = np.dot(W1, A0) + B1 # net output for hidden layer
A1 = ReLU(Z1) # applying activation function 
print(f"Net output for hidden layer neurons: \n{A1}")

Net output for hidden layer neurons: 
[[1.1]
 [1.4]
 [1.7]
 [2. ]]


In [11]:
Z2 = np.dot(W2, A1) + B2 # net output for output layer
A2 = sigmoid(Z2) # applying activation function for output layer
print(f"Net output for output layer : \n{A2}")

Net output for output layer : 
[[0.84553473]
 [0.98493201]]


In [12]:
E = compute_error(T, A2)
E_total = np.sum(E)
print(f"Total error: {E_total}")

Total error: 0.4969752914065365


**Backward pass**

In [13]:
# first calculate output layer gradient
dZ2 = (A2 - T) * A2 * (1 - A2)
dZ2

array([[-0.02017405],
       [ 0.01461732]])

In [14]:
dW2 = np.dot(dZ2, A1.T)
dW2

array([[-0.02219146, -0.02824367, -0.03429589, -0.0403481 ],
       [ 0.01607905,  0.02046425,  0.02484945,  0.02923464]])

In [15]:
# calculate Hidden layer gradient 
dZ1 = np.dot(W2.T, dZ2)
dZ1

array([[0.00529126],
       [0.00473558],
       [0.00417991],
       [0.00362424]])

In [16]:
dW1 = np.dot(dZ1, A0.T)

In [17]:
W2 = W2 - 0.01 * dW2 # update W2
print(f"New W2: \n{W2}")
B2 = B2 - 0.01 * np.sum(dZ2, axis=0, keepdims=True) * (1/4) # update Bias 2
print(f"New B2: \n{B2}")

New W2: 
[[0.10022191 0.20028244 0.30034296 0.40040348]
 [0.49983921 0.59979536 0.69975151 0.79970765]]
New B2: 
[[1.38918226e-05]]


In [18]:
W1 = W1 - 0.01 * dW1 # update W2
print(f"New W1: \n{W1}")
B1 = B1 - 0.01 * np.sum(dZ1, axis=1, keepdims=True) * (1/4) # update Bias 2
print(f"New B1: \n{B1}")

New W1: 
[[0.09994709 0.49989417]
 [0.19995264 0.59990529]
 [0.2999582  0.6999164 ]
 [0.39996376 0.79992752]]
New B1: 
[[-1.32281400e-05]
 [-1.18389578e-05]
 [-1.04497755e-05]
 [-9.06059323e-06]]
